name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Check
        uses: actions/checkout@v6
      - name: Build
        shell: cmd
        run: |
          for /f "usebackq tokens=*" %%i in (`"%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe" -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath`) do set "VS_INSTALL=%%i"
          call "%VS_INSTALL%\VC\Auxiliary\Build\vcvarsall.bat" x64
          call build.bat
      - name: Run
        shell: cmd
        run: a.exe
